[build-system]
requires = [
    "setuptools>=58.0.4",
    "wheel"
]
build-backend = "setuptools.build_meta"

# Ref: https://github.com/codespell-project/codespell#using-a-config-file
[tool.codespell]
skip = '.git,*.css'
check-hidden = true
# ignore-regex = ''
# ignore-words-list = ''
